local opt = vim.opt_local
opt.wrap = true
-- opt.linebreak = true
-- opt.nofoldenable = true
opt.spell = true
opt.showbreak = "+++"
opt.colorcolumn = "80"
vim.g.markdown_folding = 1
opt.foldenable = false
